### PR TITLE
[TASK] Upgrade to Psalm 5

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Comment by oliverklee** [comment]
We'll need to fix the Psalm issues first.

**Comment by martin-helmich** [comment]
```
------------------------------
21 errors found
------------------------------
52 other issues found.
You can display them with --show-info=true
------------------------------
```

Oh boy... 😐

**Comment by oliverklee** [comment]
My take (or professional opinion) is that using non-booleans instead of booleans is a bad thing (the same way that using `empty` is a bad thing) because some things are considered empty (or false) even though a human wouldn't expect the to. Example: https://onlinephp.io?s=s7EvyCjg5eLlykxT0FAyUNJUqObl4kxNzshXUAopKk1VjMlTsublqlVIzSlORZJzSwTyYZIA&v=8.2.13

**Comment by martin-helmich** [comment]
> My take (or professional opinion) is that using non-booleans instead of booleans (edit: as booleans in conditions) is a bad thing (the same way that using empty is a bad thing) because some things are considered empty (or false) even though a human wouldn't expect the to.

Yeah, I tend to agree... 😕  I bit the bullet and fixed everything and anything that Psalm has complained about; pipelines look good (the codeclimate check seems to be a false-positive, because some things moved around). I also decided to drop support for PHP <= 8.0 along the way, because I wanted to use some of the newer language features, and those are EOL anyway.

**Comment by oliverklee** [comment]
I think it would make sense to split this up - at least to have the PHP requirement change, the annotation streamlining, the "use real bools in conditions" and the Psalm update in separate PRs. What do you think?

**Comment by martin-helmich** [comment]
> I think it would make sense to split this up - at least to have the PHP requirement change, the annotation streamlining, the "use real bools in conditions", the native type annotations, the PHP bump on CI and the Psalm update in separate PRs

This seems difficult to untangle-- at least the PHP and Psalm change seem depend on each other in some way; just bumping PHP was attempted in https://github.com/martin-helmich/typo3-typoscript-parser/pull/89, which failed due to the old Psalm. I'll attempt to *just* bump Psalm (along with the changes required by that) on its own, but am hesitant to put too much effort into untangling all this.

**Comment by martin-helmich** [comment]
I cherry-picked the Psalm upgrade itself into #96, and then merged your original PHP bump in #89, which worked out. I've also added all sorts of cleanup in #97. I'll close this PR for now, since all changes in here are incorporated in either #96, #89 or #97.

**Pull request closed without merging**
